import "./globals.css";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import Header from "./components/header";
import StylesProvider from "./styles/StylesProvider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StylesProvider>
        <body className={outfit.className}>
          <Header />
          {children}
        </body>
      </StylesProvider>
    </html>
  );
}
